name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Delete Modules
        run: npm run deleteModules
      - name: Clear Cache
        run: npm run clearCache
      - name: Install Packages
        run: npm install
      - name: npm test:ci
        run: npm run test:ci
        env:
          CI:''
      - name: Build page
        run: npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{secrets.PERSONAL_TOKEN}}
          publish_dir: ./build
